import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import Link from "next/link";

import Header from "./components/header";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>App Corba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <section className="section-main">
          <div className="box">
            <div className="titulo">
              <h1>CORBA'S WEB</h1>
            </div>
            <nav>
              <br></br>
              <Link href="/components/main">
                <a className="text-gray-300">Entrar</a>
              </Link>
            </nav>
          </div>
        </section>
      </main>

      <style jsx>
        {`
          .titulo {
            margin: 0;
            line-height: 1.15;
            font-size: 4rem;
            color: white;
          }
          nav {
            font-size: 24px;
            text-align: center;
            color: white;
          }
          .box {
            padding: 5em;
            border: 15px solid white;
            animation: mymove 4s infinite;

            width: 100%;
          }
          @keyframes mymove {
            50% {
              box-shadow: 10px 20px 30px red;
            }
          }
        `}
      </style>
    </div>
  );
}
